### ISSUE TITLE
gulp-util should be a non-dev dependency

### ISSUE THREAD

**Issue by pascal-hofmann** [aetheric/gulp-less-precompiler#10]
gulp-util should be a non-dev dependency:

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/../node_modules/gulp-less-precompiler/src/main/plugin.js:5:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Tzrlk** [comment]
Whoops. That's an embarrassing oversight.

**Comment by Tzrlk** [comment]
Ugh, versions didn't update properly. Just need to fix the history real quick.

**Comment by pascal-hofmann** [comment]
@Tzrlk Works fine now. Thank you! :+1:
